# port 번호 바꾸기
server:
  port: 8080

#logging:
#  level:
#    org.springframework: DEBUG
spring:
  messages:
    basename: messages
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: username
      password: passw0rd
management:
  endpoints:
    web:
      exposure:
        include: "*"