# port 번호 바꾸기
server:
  port: 8080

#logging:
#  level:
#    org.springframework: DEBUG
spring:
  messages:
    basename: messages
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/restApi
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  security:
#    user:
#      name: username
#      password: passw0rd
management:
  endpoints:
    web:
      exposure:
        include: "*"